#!/bin/bash

run_brew() {
    p_header "- Updating Homebrew"
    brew update
    [[ $? ]] && p_success "Done"

    p_header "- Adding third-party repositories"
    brew tap homebrew/cask-fonts # font-jetbrains-mono
    [[ $? ]] && p_success "Done"

    p_header "- Ugrading existing cask and formulae"
    brew upgrade
    [[ $? ]] && p_success "Done"

    local list_formulae
    local -a missing_formulae
    local -a desired_formulae=(
        'awscli'
        'awscurl'
        'bat'
        'exa'
        'fd'
        'fish'
        'fzf'
        #'gdb' # No bottle (bin) for Apple Silicon.
        'gh'
        'git'
        'gnupg'
        'hey'
        'httpie'
        'jq'
        'kind'
        'neovim'
        'node@14'
        'sqlite'
        'vegeta'
    )

    local list_cask
    local -a missing_cask
    local -a desired_cask=(
        'discord'
        'font-jetbrains-mono'
        'google-chrome'
        'iterm2'
        'nosql-workbench'
        'notion'
        'signal'
        'slack'
        'tunnelblick'
        'vscodium'
    )

    for index in ${!desired_formulae[*]}
    do
        if ! formula_exists ${desired_formulae[$index]}; then
            missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
        fi
    done

    for index in ${!desired_cask[*]}
    do
        if ! cask_exists ${desired_cask[$index]}; then
            missing_cask=("${missing_cask[@]}" "${desired_cask[$index]}")
        fi
    done

    if [[ "$missing_formulae" ]]; then
        list_formulae=$( printf "%s " "${missing_formulae[@]}" )

        p_header "- Installing missing formulae"
        brew install $list_formulae
        [[ $? ]] && p_success "Done"
    fi

    if [[ "$missing_cask" ]]; then
        list_cask=$( printf "%s " "${missing_cask[@]}" )

        p_header "- Installing missing cask"
        brew install --cask $list_cask

        [[ $? ]] && p_success "Done"
    fi

    p_header "- Clean up"
    brew cleanup
    [[ $? ]] && p_success "Done"
}
