#!/bin/bash

run_brew() {

    # Check for Homebrew
    if type_exists 'brew'; then
        e_header "Updating Homebrew..."
        # Use the latest version of Homebrew
        brew update
        [[ $? ]] && e_success "Done"

        e_header "Adding third-party repositories..."
        # Add the third-party repositories required for install
        brew tap homebrew/cask-fonts # font-jetbrains-mono
        brew tap weaveworks/tap # eksctl
        [[ $? ]] && e_success "Done"

        e_header "Updating any existing Homebrew formulae..."
        # Upgrade any already-installed formulae
        brew upgrade
        [[ $? ]] && e_success "Done"

        e_header "Checking status of desired Homebrew formulae..."
        local list_formulae
        local -a missing_formulae
        local -a desired_formulae=(
            'awscli'
            'awscurl'
            'bat'
            'eksctl'
            'exa'
            'fish'
            'gh'
            'git'
            'gnupg'
            'httpie'
            'jq'
            'kubectl'
            'linkerd'
            'minikube'
            'tmux'
        )

        local list_cask
        local -a missing_cask
        local -a desired_cask=(
            'alacritty'
            'bloomrpc'
            'docker'
	        'font-jetbrains-mono'
            'google-chrome'
            'insomnia'
            'slack'
            'tunnelblick'
	        'visual-studio-code'
        )

        for index in ${!desired_formulae[*]}
        do
            if ! formula_exists ${desired_formulae[$index]}; then
                # Store the name (and options) of every missing formula
                missing_formulae=("${missing_formulae[@]}" "${desired_formulae[$index]}")
            fi
        done

        for index in ${!desired_cask[*]}
        do
            if ! cask_exists ${desired_cask[$index]}; then
                # Store the name (and options) of every missing formula
                missing_cask=("${missing_cask[@]}" "${desired_cask[$index]}")
            fi
        done

        if [[ "$missing_formulae" ]]; then
            # Convert the array of missing formula into a list of space-separate strings
            list_formulae=$( printf "%s " "${missing_formulae[@]}" )

            e_header "Installing missing Homebrew formulae..."
            # Install all missing formulae
            brew install $list_formulae

            [[ $? ]] && e_success "Done"
        fi

        if [[ "$missing_cask" ]]; then
            # Convert the array of missing formula into a list of space-separate strings
            list_cask=$( printf "%s " "${missing_cask[@]}" )

            e_header "Installing missing Homebrew cask..."
            # Install all missing cask
            brew cask install $list_cask

            [[ $? ]] && e_success "Done"
        fi

        # Remove outdated versions from the Cellar
        brew cleanup
    else
        printf "\n"
        e_error "Error: Homebrew not found."
        printf "Aborting...\n"
        exit
    fi

}
